#version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8004:8000"
    volumes:
      - ./:/app
      - ./docker-start.sh:/usr/local/bin/start
      #- ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    entrypoint: /usr/local/bin/start
    # entrypoint: php artisan octane:start --max-requests=1
    environment:
      CONTAINER_ROLE: app