<?php

return [
	// launched_at 系统上线日期，全面启用ma+alias, for check LyItem is_old or new.
    'launched_at' => env('LAUNCHED_AT', now()->subDays(5)->format('Y-m-d')),
	'lyMeta'=>[
		'extraFields' =>  [
			'text' => [
		            [
		                'field' => 'name_en',
		                'field_desc' => 'Program English Title',
		                'placeholder' => '节目英文标题',
		            ],
		            [
		                'field' => 'program_column',
		                'field_desc' => 'Program Column',
		                'placeholder' => '节目栏目',
		            ],
		            [
		                'field' => 'producer',
		                'field_desc' => 'Producer',
		                'placeholder' => '节目监制',
		            ],
		            [
		                'field' => 'program_email',
		                'field_desc' => 'Program E-mail',
		                'placeholder' => '节目电邮',
		            ],
		            [
		                'field' => 'program_sms',
		                'field_desc' => 'Program SMS Number',
		                'placeholder' => '节目短信号码',
		            ],
		            [
		                'field' => 'program_sms_keyword',
		                'field_desc' => 'Program Abbreviation For SMS',
		                'placeholder' => '节目短信用简写',
		            ],
		            [
		                'field' => 'program_phone_number',
		                'field_desc' => 'Program Phone Number',
		                'placeholder' => '节目电话号码',
		            ],
		            [
		                'field' => 'program_phone_time',
		                'field_desc' => 'Time To Receive Phone Call',
		                'placeholder' => '接听电话时间',
		            ],
		            [
		                'field' => 'program_notify_email',
		                'field_desc' => 'Email to Receive notify',
		                'placeholder' => '接受上传监控邮件',
		            ],
			],
		],
	],
	'ltsMeta'=>[
		'extraFields' =>  [
			'text' => [
	            [
	                'field' => 'name_en',
	                'field_desc' => 'LTS Subject English Title',
	                'placeholder' => '节目英文标题',
	            ],
			],
		],
	],
	'code_diff' => [
	    'ltsdp1'=>'ltstpa1',
	    'ltsdp2'=>'ltstpa2',
	    'ltshdp1'=>'ltstpb1',
	    'ltshdp2'=>'ltstpb2',
	    'ltsnp'=>'ltsnp',
	],
	'cloudfront_domain' => env('CLOUDFRONT_DOMAIN'),
	'uploader_domain' => env('UPLOADER_DOMAIN'),
	'init' => [
		'schedule' => [
			"aw"=>"SU",
			"bc"=>"MO,TU,WE,TH,FR",
			"be"=>"MO,TU,WE,TH,FR,SA,SU",
			"bs"=>"SA,SU",
			"bx"=>"SA,SU",
			"cc"=>"MO,TU,WE,TH,FR",
			"cs"=>"SU",
			"cttb"=>"MO,TU,WE,TH,FR",
			"cw"=>"MO,TU,WE,TH,FR",
			"cwa"=>"SA,SU",
			"dr"=>"SA,SU",
			"ds"=>"MO,TU,WE,TH,FR",
			"dy"=>"MO,TU,WE,TH,FR",
			"ec"=>"MO,TU,WE,TH,FR",
			"ee"=>"MO,TU,WE,TH,FR,SA,SU",
			"fa"=>"MO,TU,WE,TH,FR,SA,SU",
			"fd"=>"FR",
			"fh"=>"SA,SU",
			"fp"=>"WE,TH",
			"gf"=>"MO,TU,WE,TH,FR",
			"gg"=>"MO,TU,WE,TH,FR",
			"gt"=>"MO,TU,WE,TH,FR,SA,SU",
			"hmw"=>"MO,TU,WE,TH,FR",
			"hr"=>"MO,TU,WE,TH,FR",
			"iba"=>"SA,SU",
			"ir"=>"SA,SU",
			"it"=>"MO,TU,WE,TH,FR",
			"ka"=>"MO,TU,WE,TH,FR,SA,SU",
			"ls"=>"SA,SU",
			"mg"=>"SA",
			"mn"=>"MO,TU,WE,TH,FR",
			"mpa"=>"SA,SU",
			"mw"=>"MO,TU,WE,TH,FR,SA,SU",
			"pc"=>"MO,TU,WE,TH,FR,SA",
			"pm"=>"MO,TU,WE,TH,FR",
			"pp"=>"SA,SU",
			"pt"=>"SA,SU",
			"rt"=>"SA,SU",
			"sa"=>"SA,SU",
			"sc"=>"SA,SU",
			"sz"=>"MO,TU,WE,TH,FR",
			"th"=>"MO,TU,WE,TH,FR,SA,SU",
			"tmw"=>"MO,TU,WE,TH,FR",
			"ttb"=>"MO,TU,WE,TH,FR",
			"tv"=>"MO,TU",
			"up"=>"MO,TU,WE,TH,FR",
			"ut"=>"MO,TU,WE,TH,FR",
			"vp"=>"SA",
			"wa"=>"SA,SU",
			"wc"=>"SA,SU",
			"wr"=>"MO,TU,WE,TH,FR",
			"ws"=>"MO,TU,WE,TH,FR",
			"yb"=>"FR",
			"ym"=>"SA,SU",
			"ynf"=>"MO,TU,WE,TH,FR,SA,SU",
			"yp"=>"SA",
			"yy"=>"MO,TU",
			"maltsnp"=>"MO,TU,WE,TH,FR,SA",
			"maltsdp1"=>"MO,TU,WE,TH,FR,SA",
			"maltsdp2"=>"MO,TU,WE,TH,FR,SA",
			"maltshdp1"=>"MO,TU,WE,TH,FR,SA",
			"maltshdp2"=>"MO,TU,WE,TH,FR,SA",
		],
	],
];